### ISSUE TITLE
Export saved job list as CSV error

### ISSUE THREAD

**Issue by Scarvy** [Su24-CS5004-Online-Lionelle/final-project-group-3#9]
Export as CSV error message

<img width="1310" alt="Screenshot 2024-08-05 at 10 40 05 PM" src="https://github.com/user-attachments/assets/7f5e67ca-13bf-49eb-9f74-bf0362644f26">

**Comment by Scarvy** [comment]
I have a feeling it has to do with the nested structure of the POJO

**Comment by asnts18** [comment]
https://github.com/Su24-CS5004-Online-Lionelle/final-project-group-3/pull/10
